# Generated by Django 5.1.2 on 2024-11-14 06:29

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password

def create_initial_data(apps, schema_editor):
    supuser = apps.get_model("account", "User")
    module = apps.get_model("main", "Module")
    submodule = apps.get_model("main", "Submodule")
    section = apps.get_model("main", "Section")
    topic = apps.get_model("main", "Topic")
    quiz = apps.get_model("main", "Quiz")
    question = apps.get_model("main", "Question")
    option = apps.get_model("main", "Option")
    quiz_attempt = apps.get_model("main", "Quiz_attempt")
    response = apps.get_model("main", "Response")

    #modules
    m_h = f"""Study of human health, disease prevention, and medical treatment, encompassing clinical practice, \
public health, anatomy, physiology, pharmacology, and healthcare systems. Includes specialties like nursing, \
dentistry, and veterinary science."""
    s_t = f"""Exploration of natural and physical sciences including biology, chemistry, physics, and their \
technological applications. Covers scientific research methods, laboratory techniques, and emerging \
technologies in fields like biotechnology and materials science."""
    e = f"""Application of scientific and mathematical principles to design, build, and optimize solutions \
to technical challenges. Includes mechanical, electrical, civil, and chemical engineering, focusing on \
infrastructure, machines, processes, and systems."""
    ss_h = f"""Study of human society, behavior, culture, and creative expression. Encompasses psychology, \
sociology, anthropology, history, philosophy, and religious studies. Examines how people interact, communicate, \
and develop social structures."""
    b_m = f"""Study of organizational operations, strategy, and leadership in commercial and non-profit contexts. \
Covers finance, marketing, operations, human resources, entrepreneurship, and strategic planning for organizational success."""
    a_l = f"""Creative and analytical study of human artistic expression through visual arts, music, theater, dance, \
and written works. Includes art history, creative writing, literary analysis, and performing arts."""
    i_t = f"""Study of computing systems, software development, data management, and digital networks. \
Focuses on designing, implementing, and maintaining technology solutions for business and society, \
including cybersecurity, artificial intelligence, and cloud computing."""
    l_l = f"""Acquisition and mastery of languages through study of grammar, vocabulary, pronunciation, \
and cultural context. Includes both theoretical linguistics and practical communication skills in foreign languages."""
    
    user  = supuser.objects.create(
        id = 1,
        email = 'ayogublossomisrael@gmail.com',
        first_name = 'Blossom',
        last_name = 'Ayogu',
        is_verified = True,
        is_superuser = True,
        user_role = 'SUP',
        password = make_password('password123')
    )
    user1  = supuser.objects.create(
        id = 2,
        email = 'edu@gmail.com',
        first_name = 'Blossom',
        last_name = 'Ayogu',
        is_verified = True,
        is_superuser = False,
        user_role = 'EDU',
        password = make_password('password123')
    )
    user2  = supuser.objects.create(
        id = 3,
        email = 'stu@gmail.com',
        first_name = 'Blossom',
        last_name = 'Ayogu',
        is_verified = True,
        is_superuser = False,
        user_role = 'STU',
        password = make_password('password123')
    )
    m1, _ = module.objects.update_or_create(pk=1, defaults={"title": "Medicine & Health Sciences", "description": m_h})
    module.objects.update_or_create(pk=2, defaults={"title": "Science & Technology", "description": s_t})
    module.objects.update_or_create(pk=3, defaults={"title": "Engineering", "description": e})
    module.objects.update_or_create(pk=4, defaults={"title": "Social Sciences & Humanities", "description": ss_h})
    module.objects.update_or_create(pk=5, defaults={"title": "Business & Management", "description": b_m})
    module.objects.update_or_create(pk=6, defaults={"title": "Arts & Literature", "description": a_l})
    module.objects.update_or_create(pk=7, defaults={"title": "Information Technology", "description": i_t})
    module.objects.update_or_create(pk=8, defaults={"title": "Language Learning", "description": l_l})

    s1, _ = submodule.objects.update_or_create(pk=1, defaults={"module_id": m1, "title": "Medicine & Health Sciences", "description": m_h})

    se1, _ = section.objects.update_or_create(pk=1, defaults={"submodule_id": s1, "title": "Medicine & Health Sciences", "description": m_h})

    t1, _ = topic.objects.update_or_create(pk=1, defaults={"section_id": se1, "title": "Medicine & Health Sciences", "description": m_h})
    
    q1, _ = question.objects.update_or_create(question_type='PAQ', question='What is the capital of nigeria', module_id=m1)
    q2, _ = question.objects.update_or_create(question_type='PAQ', question='What is the capital of ghana', submodule_id=s1,)
    
    option.objects.update_or_create(id=1, question_id=q1, is_answer=False, option='lagos')
    o1, _ = option.objects.update_or_create(id=2, question_id=q1, is_answer=True, option='abuja')
    option.objects.update_or_create(id=3, question_id=q1, is_answer=False, option='ogun')
    option.objects.update_or_create(id=4, question_id=q1, is_answer=False, option='enugu')
    
    option.objects.update_or_create(id=5, question_id=q2, is_answer=False, option='kumasi')
    o2, _ = option.objects.update_or_create(id=6, question_id=q2, is_answer=True, option='accra')
    option.objects.update_or_create(id=7, question_id=q2, is_answer=False, option='ashanti')
    option.objects.update_or_create(id=8, question_id=q2, is_answer=False, option='north kumasi')

    quiz, _ = quiz.objects.update_or_create(pk=1, defaults={
        'name': 'initial',
        'num_of_questions': 2,
        'module_id': m1,
        'submodule_id': s1,
        'section_id': se1,
        'topic_id': t1,
        'created_by': user1
        })
    quiz.questions.set([q1, q2])
    
    qa, _ = quiz_attempt.objects.update_or_create(pk=1, defaults={'quiz_id': quiz, 'taken_by': user2, 'score': 2, 'status': 'FIN', })

    response.objects.update_or_create(pk=1, defaults={'quiz_attempt': qa, 'question_id': q1, 'chosen_option': o1})
    response.objects.update_or_create(pk=2, defaults={'quiz_attempt': qa, 'question_id': q2, 'chosen_option': o2})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('AIG', 'AI Generated'), ('EDQ', 'Educator'), ('PAQ', 'Past question')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('EAS', 'Easy'), ('MED', 'Medium'), ('HRD', 'Hard')], default='EAS', max_length=3)),
                ('question', models.TextField()),
                ('created_by', models.ForeignKey(default=main.models.get_super_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.module')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answer', models.BooleanField(default=False)),
                ('option', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('num_of_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=main.models.get_super_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.module')),
                ('questions', models.ManyToManyField(to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('FIN', 'Completed'), ('STA', 'Not started'), ('MID', 'Not completed')], default='MID', max_length=3)),
                ('time_taken', models.DateTimeField(auto_now_add=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.quiz')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_taken'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz_attempt')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=main.models.get_super_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
        migrations.AddField(
            model_name='question',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.section'),
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=main.models.get_super_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.module')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='submodule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.submodule'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='submodule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.submodule'),
        ),
        migrations.AddField(
            model_name='question',
            name='submodule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.submodule'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=main.models.get_super_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.section')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.topic'),
        ),
        migrations.RunPython(create_initial_data),
    ]
